name: unsloth

services:
  unsloth:
    image: unsloth/unsloth-zscaler:local
    build:
      context: .
      dockerfile: Dockerfile.zscaler
    container_name: unsloth
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "8000:8000"
      - "2222:22"
    environment:
      - JUPYTER_PASSWORD=ReexamineRetiredFeistyGuacamole
      - UNSLOTH_STUDIO_PASSWORD=ReexamineRetiredFeistyGuacamole
      - HF_HUB_DISABLE_XET=1
    volumes:
      - ./work:/workspace/work
      - ./notebooks:/workspace/unsloth-notebooks
      - "${USERPROFILE}/Models:/workspace/models:ro"
      - unsloth_studio_home:/opt/unsloth-studio
      - unsloth_huggingface:/workspace/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  unsloth_studio_home:
    external: true
  unsloth_huggingface:
    external: true